/**
 * Canonical data plan for the type-booth catalog (P86/P87/T04..T25) — "KATALOG / DB TYPOVÝCH
 * STÁNKŮ" session, 2026-08-19. Pure planning logic only (no I/O): given the real catalog_items
 * rows already in the DB, decide CREATE/UPDATE/NOOP per code and produce the exact patch —
 * never a wholesale document rewrite, always preserving every unknown field (pricingEntries,
 * sourceKey, sourceSystem, parts, printSurfaces, ...) that already lives on the row.
 *
 * Explicitly NOT touched by this module: pricing (base pricingEntries, event pricing_entries,
 * price lists), catalog_mappings, any asset upload — those stay exactly as they are.
 */
import type { BoothVariant, CatalogItemKind, CatalogItemStatus } from "./models.ts";

export const P86_INTERNAL_CODE = "P86";
export const P87_INTERNAL_CODE = "P87";

/** The 10 real Txx type-booth lines already living in catalog_items as of the 2026-08-14 import (Batch #2B) — never invented, matches the live DB audit. */
export const TYPE_BOOTH_LINE_CODES = ["T04", "T06", "T09", "T12", "T15", "T16", "T18", "T20", "T24", "T25"] as const;
export type TypeBoothLineCode = (typeof TYPE_BOOTH_LINE_CODES)[number];

/** Generic placeholder variant count for Txx lines with NO confirmed real spec yet (everything except T04 — see TYPE_BOOTH_LINE_SPECS below). Not a claim about the real construction, only a structural scaffold pending real data. */
export const TYPE_BOOTH_VARIANT_COUNT = 4;

export type ExistingCatalogItemRow = Readonly<{
  id: string;
  internalCode: string | null;
  kind: string;
  lifecycleStatus: string;
  displayName: string;
  category: string | null;
  document: Readonly<Record<string, unknown>>;
}>;

function isValidVariantEntry(value: unknown): value is BoothVariant {
  if (!value || typeof value !== "object") return false;
  const candidate = value as Record<string, unknown>;
  return typeof candidate.id === "string" && Boolean(candidate.id) && typeof candidate.name === "string" && Boolean(candidate.name);
}

/** True only if the document already carries a real, validly-shaped variants array — an empty array (P86) or a malformed one never counts. */
export function documentHasVariants(document: Readonly<Record<string, unknown>>): boolean {
  const value = document.variants;
  return Array.isArray(value) && value.length > 0 && value.every(isValidVariantEntry);
}

/**
 * Deterministic, stable variant identity scoped to the parent line — e.g. "t04-v1".."t04-v4".
 * Never a bare array index: the id is baked into the object itself, so reordering the array can
 * never change which variant a stored modelAsset/photoAsset belongs to. No real ABF variant
 * codes exist for these, so generic "Varianta N" naming is used deliberately (same convention
 * data/booths.ts already uses for its own placeholder T6 variants) — never invented semantics
 * like "corner"/"inline".
 */
export function buildGenericVariants(internalCode: string, count: number = TYPE_BOOTH_VARIANT_COUNT): readonly BoothVariant[] {
  const prefix = internalCode.toLowerCase();
  return Array.from({ length: count }, (_, index) => ({
    id: `${prefix}-v${index + 1}`,
    name: `Varianta ${index + 1}`,
  }));
}

/** Prefix shared by every auto-generated Txx description this module writes — lets a later run tell "our own old auto-text, safe to upgrade" apart from "an admin typed something real here, never touch it". */
const AUTO_DESCRIPTION_PREFIX = "Typová konstrukce Octanorm";

function isAutoGeneratedDescription(value: unknown): boolean {
  return typeof value === "string" && value.startsWith(AUTO_DESCRIPTION_PREFIX);
}

/** Factual only — echoes the DB's own official-name pattern ("Typový stánek octanorm - T4"). No invented technical features. */
export function typeBoothLineDescription(internalCode: string, confirmed: boolean): string {
  return confirmed
    ? `${AUTO_DESCRIPTION_PREFIX} ${internalCode}, tři varianty provedení: roh vlevo, roh vpravo, řadová/přímá. Bez zázemí.`
    : `${AUTO_DESCRIPTION_PREFIX} ${internalCode} — počet a typ variant zatím nejsou potvrzeny (zástupné varianty čekají na doplnění reálných dat).`;
}

/**
 * T04's REAL confirmed variant set (session 2026-08-19, given directly by the domain expert —
 * never inferred): exactly 3 variants, no back-of-house/"zázemí" variant exists for T04. Stable
 * ids scoped to the line; semantic names reflect the real construction, not generic "Varianta N"
 * placeholders (those stay reserved for lines with no confirmed spec yet — see
 * buildGenericVariants).
 */
export const T04_CONFIRMED_VARIANTS: readonly BoothVariant[] = [
  { id: "t04-corner-left", name: "Roh – levý" },
  { id: "t04-corner-right", name: "Roh – pravý" },
  { id: "t04-inline", name: "Řada / přímý" },
];

export type TypeBoothLineSpec = Readonly<{
  variants: readonly BoothVariant[];
  /** true = a real, human-confirmed variant set (T04 only, so far). false = generic scaffold, count/semantics not yet verified — see documentVariantsConfirmed. */
  confirmed: boolean;
}>;

/** The per-line variant spec this migration targets. Only T04 has a confirmed real spec today; every other Txx line stays on the generic 4-variant scaffold until real data is provided (see session decision log, 2026-08-19: "keep 4 generic, mark needs_review"). */
export function typeBoothLineSpec(code: TypeBoothLineCode): TypeBoothLineSpec {
  if (code === "T04") return { variants: T04_CONFIRMED_VARIANTS, confirmed: true };
  return { variants: buildGenericVariants(code), confirmed: false };
}

export const P87_CANONICAL = {
  internalCode: P87_INTERNAL_CODE,
  displayName: "Kóje 2 × 3 m",
  category: "Canonical",
  widthMm: 2000,
  depthMm: 3000,
  description: "Základní otevřená veletržní kóje 2 × 3 m.",
} as const;

export type CanonicalPlanAction = "create" | "update" | "noop";

export type CanonicalInsertRow = Readonly<{
  internal_code: string;
  kind: CatalogItemKind;
  lifecycle_status: CatalogItemStatus;
  display_name: string;
  official_name: null;
  category: string;
  unit: null;
  document: Readonly<Record<string, unknown>>;
}>;

export type CanonicalPlanEntry = Readonly<{
  internalCode: string;
  action: CanonicalPlanAction;
  reason: string;
  targetId?: string;
  /** UPDATE only — merged shallowly onto the EXISTING document, never a replacement. */
  documentPatch?: Readonly<Record<string, unknown>>;
  insertRow?: CanonicalInsertRow;
}>;

function findByInternalCode(existing: readonly ExistingCatalogItemRow[], code: string): ExistingCatalogItemRow | undefined {
  const upper = code.toUpperCase();
  return existing.find((row) => (row.internalCode ?? "").toUpperCase() === upper || (row.document.internalCode as string | undefined)?.toUpperCase() === upper);
}

/** P86 is already a complete canonical booth — this migration never touches it; only confirms its presence. */
export function planP86(existing: readonly ExistingCatalogItemRow[]): CanonicalPlanEntry {
  const row = findByInternalCode(existing, P86_INTERNAL_CODE);
  if (!row) {
    return { internalCode: P86_INTERNAL_CODE, action: "noop", reason: "P86 nenalezeno v DB — mimo scope této migrace (nikdy nevytvářet nový P86)." };
  }
  return { internalCode: P86_INTERNAL_CODE, action: "noop", reason: `P86 už je canonical (id=${row.id}, kind=${row.kind}, category=${row.category}) — žádná změna.` };
}

/** CREATE only if truly absent — never a second P87, ever (idempotent by internalCode lookup). */
export function planP87(existing: readonly ExistingCatalogItemRow[]): CanonicalPlanEntry {
  const row = findByInternalCode(existing, P87_INTERNAL_CODE);
  if (row) {
    return { internalCode: P87_INTERNAL_CODE, action: "noop", reason: `P87 už existuje (id=${row.id}) — nevytvářím duplicitu.` };
  }
  return {
    internalCode: P87_INTERNAL_CODE,
    action: "create",
    reason: "P87 neexistuje — vytvářím nový canonical stub, lifecycle_status=needs_review. Záměrně BEZ výšky/ceny/GLB/photoAsset/sourceAssets — žádná z těchto hodnot není potvrzená.",
    insertRow: {
      internal_code: P87_CANONICAL.internalCode,
      kind: "booth",
      lifecycle_status: "needs_review",
      display_name: P87_CANONICAL.displayName,
      official_name: null,
      category: P87_CANONICAL.category,
      unit: null,
      document: {
        displayName: P87_CANONICAL.displayName,
        name: P87_CANONICAL.displayName,
        category: P87_CANONICAL.category,
        catalogItemKind: "booth",
        internalCode: P87_CANONICAL.internalCode,
        widthMm: P87_CANONICAL.widthMm,
        depthMm: P87_CANONICAL.depthMm,
        description: P87_CANONICAL.description,
      },
    },
  };
}

function currentVariantIds(document: Readonly<Record<string, unknown>>): readonly string[] {
  const value = Array.isArray(document.variants) ? document.variants.filter(isValidVariantEntry) : [];
  return value.map((variant) => variant.id).slice().sort();
}

function sameIdSet(a: readonly string[], b: readonly string[]): boolean {
  return a.length === b.length && a.every((id, index) => id === b[index]);
}

/**
 * UPDATE only the `document` column — never display_name/category/kind/lifecycle_status columns,
 * never pricingEntries/sourceSystem/sourceKey/any other document key. Idempotent against the
 * REAL target spec (typeBoothLineSpec), not just "has some variants array": a line whose variants
 * don't match the spec's exact id set, or whose `variantsConfirmed` flag doesn't match the spec's
 * confirmed-ness, is corrected — this is what lets a genuine data correction (e.g. T04 going from
 * an old 4-generic scaffold to its real, confirmed 3-variant set) actually apply, while a line
 * already matching the spec stays a no-op forever. The auto-generated description is only ever
 * replaced when it still carries THIS module's own AUTO_DESCRIPTION_PREFIX (or is entirely
 * absent) — a description an admin typed by hand is never touched.
 */
export function planTypeBoothLine(existing: readonly ExistingCatalogItemRow[], code: TypeBoothLineCode): CanonicalPlanEntry {
  const row = findByInternalCode(existing, code);
  if (!row) {
    return { internalCode: code, action: "noop", reason: `${code} nenalezeno v DB — mimo scope (tato migrace nikdy nevytváří nové Txx řádky).` };
  }
  if (row.kind !== "booth") {
    return { internalCode: code, action: "noop", reason: `${code} má kind="${row.kind}" (ne "booth") — vyžaduje ruční rozhodnutí, migrace kind automaticky nemění.` };
  }

  const spec = typeBoothLineSpec(code);
  const targetIds = spec.variants.map((variant) => variant.id).slice().sort();
  const idsMatch = sameIdSet(currentVariantIds(row.document), targetIds);
  const confirmedFlagMatches = row.document.variantsConfirmed === spec.confirmed;

  if (idsMatch && confirmedFlagMatches) {
    return {
      internalCode: code,
      action: "noop",
      reason: `${code} už odpovídá cílové specifikaci (${spec.variants.length} variant, confirmed=${spec.confirmed}) — idempotentní no-op.`,
    };
  }

  const patch: Record<string, unknown> = { variants: spec.variants, variantsConfirmed: spec.confirmed };
  if (!row.document.description || isAutoGeneratedDescription(row.document.description)) {
    patch.description = typeBoothLineDescription(code, spec.confirmed);
  }
  const changeKind = idsMatch ? "aktualizuji confirmed flag" : "nahrazuji variant set";
  return {
    internalCode: code,
    action: "update",
    reason: `${code}: ${changeKind} na ${spec.variants.length} variant (${spec.variants.map((v) => v.id).join(", ")}), confirmed=${spec.confirmed}, bez GLB/SKP/photo (žádný asset nevymýšlím)${patch.description ? " + description" : ""}.`,
    targetId: row.id,
    documentPatch: patch,
  };
}

export function planAllTypeBoothLines(existing: readonly ExistingCatalogItemRow[]): readonly CanonicalPlanEntry[] {
  return TYPE_BOOTH_LINE_CODES.map((code) => planTypeBoothLine(existing, code));
}

export function planTypeBoothCatalog(existing: readonly ExistingCatalogItemRow[]): readonly CanonicalPlanEntry[] {
  return [planP86(existing), planP87(existing), ...planAllTypeBoothLines(existing)];
}
